---
- name: Converge
  hosts: all
  vars:
    mongodb_pkg_install: false
    mongodb_version: "{{ lookup('env', 'MONGODB_VERSION') }}"
  pre_tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install tzdata to populate /usr/share/zoneinfo
      ansible.builtin.package:
        name: tzdata
  tasks:
    - name: "Include ansible-role-mongodb-install"
      ansible.builtin.include_role:
        name: "ansible-role-mongodb-install"
