- name: Install python3 venv tools
  ansible.builtin.package:
    name:
      - "{{ (ansible_pkg_mgr == 'apt') | ternary('python3-venv', 'python3-virtualenv') }}"
      - python3-packaging # required for debian installs
    state: present

- name: Ensure python3 is installed
  ansible.builtin.package:
    name: python3
    state: present

- name: Create virtualenv
  ansible.builtin.command: python3 -m venv /opt/mongodb_venv
  args:
    creates: /opt/mongodb_venv

- name: Install pymongo into virtualenv
  ansible.builtin.pip:
    name: pymongo
    version: "{{ mongodb_pymongo_pip_version | default(omit) }}"
    executable: /opt/mongodb_venv/bin/pip
