- name: Restart MongoDB
  ansible.builtin.service:
    name: mongod
    state: restarted

- name: Wait when MongoDB is started
  ansible.builtin.wait_for:
    host: "{{ item }}"
    port: "{{ mongodb_net_port }}"
    timeout: 30
  with_items: "{{ mongodb_net_bindip.split(',') | map('replace', '0.0.0.0', '127.0.0.1') | list }}"