name: CD
on:
  workflow_dispatch:
    inputs:
      manual_deploy:
        description: "deploy to ansible galaxy"
        default: false
        required: true
        type: boolean
  pull_request:
    branches: [main]
    types: [closed]
    paths-ignore:
      - "LICENSE"
      - "README.md"

jobs:
  deploy:
    if: ${{ github.event.pull_request.merged == true || inputs.manual_deploy == true }}
    uses: ./.github/workflows/deploy.yml
    secrets:
      API_KEY: ${{ secrets.GALAXY_API_KEY }}
