name: Lint
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths-ignore:
      - "LICENSE"
      - "README.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install ansible-lint pylint

      - name: Lint using yamllint
        run: yamllint .

      - name: Lint using ansible-lint
        run: ansible-lint .

      - name: Lint using pylint
        run: pylint $(git ls-files '*.py') --disable=C0114,C0301
